[workspace]
members = [
    "crates/app-core",
    "crates/capture-linux",
    "crates/capture-macos",
    "crates/signaling-server",
    "crates/transport-webrtc",
    "apps/cli",
]
default-members = [
    "crates/app-core",
    "crates/capture-linux",
    "crates/capture-macos",
    "crates/signaling-server",
    "crates/transport-webrtc",
    "apps/cli",
]
resolver = "2"
