[package]
name = "app-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "app_core"
path = "src/lib.rs"

[dependencies]
capture-core = { path = "../capture-core" }
capture-linux = { path = "../capture-linux" }
capture-macos = { path = "../capture-macos" }
transport-webrtc = { path = "../transport-webrtc" }
